---
AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  TeamName:
    Type: String
  DnsRootDomain:
    Type: String
  VpcCidr:
    Type: String
  VpcSubnetAz1aCidr:
    Type: String
  VpcSubnetAz1bCidr:
    Type: String
  VpcSubnetAz1cCidr:
    Type: String

Resources:

  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCidr
      EnableDnsSupport: 'true'
      EnableDnsHostnames: 'false'
      InstanceTenancy: default
      Tags:
        - Key: Name
          Value: !Sub "${TeamName}"

  InternetGateway:
    Type: AWS::EC2::InternetGateway

  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway

  RouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
      - Key: Name
        Value: !Sub "${TeamName}-RouteTablePublic"

  RoutePublic:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref RouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

  # SUBNET EU-CENTRAL-1A PUBLIC
  SubnetAz1aPublic:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      MapPublicIpOnLaunch: true
      CidrBlock: !Ref VpcSubnetAz1aCidr
      AvailabilityZone: "eu-central-1a"
      Tags:
      - Key: Name
        Value: !Sub "${TeamName}-public [eu-central-1a]"
  RouteTableAssociationAz1aPublic:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref SubnetAz1aPublic
      RouteTableId: !Ref RouteTable

  # SUBNET EU-CENTRAL-1B PUBLIC
  SubnetAz1bPublic:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      MapPublicIpOnLaunch: true
      CidrBlock: !Ref VpcSubnetAz1bCidr
      AvailabilityZone: "eu-central-1b"
      Tags:
      - Key: Name
        Value: !Sub "${TeamName}-public [eu-central-1b]"
  RouteTableAssociationAz1bPublic:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref SubnetAz1bPublic
      RouteTableId: !Ref RouteTable

  # SUBNET EU-CENTRAL-1C PUBLIC
  SubnetAz1cPublic:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      MapPublicIpOnLaunch: true
      CidrBlock: !Ref VpcSubnetAz1cCidr
      AvailabilityZone: "eu-central-1c"
      Tags:
      - Key: Name
        Value: !Sub "${TeamName}-public [eu-central-1c]"
  RouteTableAssociationAz1cPublic:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref SubnetAz1cPublic
      RouteTableId: !Ref RouteTable

Outputs:

  VPCId:
    Export:
      Name: !Sub "${AWS::StackName}-VPCId"
    Value: !Ref VPC
  VPCCidr:
      Export:
        Name: !Sub "${AWS::StackName}-VPCCidr"
      Value: !Ref VpcCidr

  HostedZoneName:
    Export:
      Name: !Sub "${AWS::StackName}-HostedZoneName"
    Value: !Sub "${TeamName}.${DnsRootDomain}"

  SubnetAz1aPublicId:
    Export:
      Name: !Sub "${AWS::StackName}-SubnetAz1aPublicId"
    Value: !Ref SubnetAz1aPublic
  SubnetAz1bPublicId:
    Export:
      Name: !Sub "${AWS::StackName}-SubnetAz1bPublicId"
    Value: !Ref SubnetAz1bPublic
  SubnetAz1cPublicId:
    Export:
      Name: !Sub "${AWS::StackName}-SubnetAz1cPublicId"
    Value: !Ref SubnetAz1cPublic
